version: "3.9"
services:
  server:
    build: .
    ports:
      - "17177:17177"   # HTTPS exposed from container
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/analytics?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - TLS_CERT=/etc/letsencrypt/live/analytics.winapps.io/fullchain.pem
      - TLS_KEY=/etc/letsencrypt/live/analytics.winapps.io/privkey.pem
    volumes:
      # Mount LetsEncrypt certs read‑only
      - /etc/letsencrypt/live/analytics.winapps.io:/etc/letsencrypt/live/analytics.winapps.io:ro
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  db-data: